### ISSUE TITLE
Module path should be "github.com/BBVA/raft-badger", not "github.com/bbva/raft-badger"

### ISSUE THREAD

**Issue by KateGo520** [BBVA/raft-badger#6]
## Background
Module path is inconsistent with go import path.
GO111MODULE=on, as [doc](https://godoc.org/github.com/BBVA/raft-badger) said, import "github.com/BBVA/raft-badger", then get this error:

```
go: finding module for package github.com/BBVA/raft-badger
go: downloading github.com/BBVA/raft-badger v1.0.1
go: found github.com/BBVA/raft-badger in github.com/BBVA/raft-badger v1.0.1
go: test1 imports
        github.com/BBVA/raft-badger: github.com/BBVA/raft-badger@v1.0.1: parsing go.mod:
        module declares its path as: github.com/bbva/raft-badger
                but was required as: github.com/BBVA/raft-badger 
```

###  Fix the module path:
1) Rename the module path to "github.com/BBVA/raft-badger": https://github.com/BBVA/raft-badger/blob/master/go.mod#L1 
```
module github.com/BBVA/raft-badger
go 1.14
require (
	…
) 

```
2) Change the [doc](https://godoc.org/github.com/BBVA/raft-badger) document to use `import "github.com/bbva/raft-badger"`.

**Comment by KateGo520** [comment]
@fernandezvara  @aalda  Could you help me review this issue? Thx :p

**Comment by aalda** [comment]
I just released a new version fixing the module path. Thanks for the warning.

**Comment by KateGo520** [comment]
@aalda  Thanks for your efforts and feedback.
